### ISSUE TITLE
Query UniProt using Entry Name

### ISSUE THREAD

**Issue by kevinwang09** [Bioconductor/UniProt.ws#12]
I am trying to make a query to UniProtKB using the Entry Name and retrieve the corresponding ID (i.e. entry as defined on the UniProt website). While I know Entry Name is not "stable", but unfortunately, it is all I have been given for a data. Is this possible given the current implementation?

```
database <- UniProt.ws(taxId = 9606)
select(x = database,  
            keys = "ALBU_HUMAN", 
            columns = c("ENTRY-NAME", "ENTRY"), 
            keytype = "UNIPROTKB")
```

Thanks!

**Comment by lshep** [comment]
Entry-name is not a valid keytype.  So the following would not work: 
```
select(x = database,  
            keys = "ALBU_HUMAN", 
            columns = c("ENTRY-NAME", "ENTRY"), 
            keytype = "ENTRY-NAME")
```

You can get the columns that could be used as keytypes by doing  `keytypes(database)` .  If the only data you have is Entry-name I might also suggest posting on the Bioconductor support site as the community might have some ideas on how to extract this information better.
