### ISSUE TITLE
A suggestion about keytypes in Uniprot.ws

### ISSUE THREAD

**Issue by HarwayZ** [Bioconductor/UniProt.ws#13]
If we have a gene name, e.g. BRCA1, we cannot to retrieve any information using `Uniprot.ws` because the _keytypes_ don't contain _GENENAME_, _gene symbol (like, hgnc_symbol)_ or other ID format. However, the **Uniprot** database provide _Gene name_ in their _ID Retrieving/mapping_ program.  Besides, I wish columns or keytypes could be classified into categories as database shown.

**Comment by mtmorgan** [comment]
Please ask questions about package use on the support site https://support.bioconductor.org
