### ISSUE TITLE
Missing IDs

### ISSUE THREAD

**Issue by Fred-White94** [Bioconductor/UniProt.ws#15]
Hi, great package generally but I see for example a tomato ENSEMBL_GENOME ID Solyc01g090660.2 which can be found on the uniprot website and has a uniprot ID of D0UDC1 is lost when using the package. Any idea why that might be? Is the website more updated than the package? In fact there are nearly 1000 IDs that are lost when using the package, at least some of which can be found on the website.

Thanks,
Fred.

**Comment by LiNk-NY** [comment]
This works as of `2.37.1`

```r
> queryUniProt(query = "D0UDC1", fields = c("accession", "id"))
   Entry   Entry.Name
1 D0UDC1 D0UDC1_SOLLC
```
