### ISSUE TITLE
Issue with UniProt.ws::select()

### ISSUE THREAD

**Issue by vw087** [Bioconductor/UniProt.ws#16]
Following is my code

#load uniprot object taxId 9606 is for human
hu <- UniProt.ws(taxId = 9606)

#extract all the ENTREZ_gene names from hu

egs = keys(hu, "ENTREZ_GENE")

## use select to extract data by the keys (Keylist) of interest

res <- UniProt.ws::select(hu, keys = keylist, columns = c("ENTRY-NAME","SEQUENCE"),keytype = "ENTREZ_GENE")

---------------------------------------------------------

I get the following error

Getting mapping data for 28976 ... and ACC
error while trying to retrieve data in chunk 1:
    no results after 5 attempts; please try again later
continuing to try
Error in `colnames<-`(`*tmp*`, value = `*vtmp*`) : 
  attempt to set 'colnames' on an object with less than two dimensions

-------------------------------------------------------------
Session info
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] sqldf_0.4-11        gsubfn_0.7          proto_1.0.0         annotables_0.1.91  
 [5] tibble_3.1.3        dplyr_1.0.7         UniProt.ws_2.32.0   BiocGenerics_0.38.0
 [9] RCurl_1.98-1.3      RSQLite_2.2.7      

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7             prettyunits_1.1.1      png_0.1-7             
 [4] ps_1.6.0               Biostrings_2.60.2      assertthat_0.2.1      
 [7] rprojroot_2.0.2        utf8_1.2.2             BiocFileCache_2.0.0   
[10] chron_2.3-56           R6_2.5.0               GenomeInfoDb_1.28.1   
[13] stats4_4.1.0           httr_1.4.2             pillar_1.6.2          
[16] zlibbioc_1.38.0        rlang_0.4.11           curl_4.3.2            
[19] rstudioapi_0.13        callr_3.7.0            blob_1.2.2            
[22] S4Vectors_0.30.0       desc_1.3.0             devtools_2.4.2        
[25] stringr_1.4.0          bit_4.0.4              compiler_4.1.0        
[28] pkgconfig_2.0.3        pkgbuild_1.2.0         tcltk_4.1.0           
[31] tidyselect_1.1.1       KEGGREST_1.32.0        GenomeInfoDbData_1.2.6
[34] IRanges_2.26.0         fansi_0.5.0            crayon_1.4.1          
[37] dbplyr_2.1.1           withr_2.4.2            bitops_1.0-7          
[40] rappdirs_0.3.3         lifecycle_1.0.0        DBI_1.1.1             
[43] magrittr_2.0.1         cli_3.0.1              stringi_1.7.3         
[46] cachem_1.0.5           XVector_0.32.0         fs_1.5.0              
[49] remotes_2.4.0          testthat_3.0.4         ellipsis_0.3.2        
[52] filelock_1.0.2         generics_0.1.0         vctrs_0.3.8           
[55] tools_4.1.0            bit64_4.0.5            Biobase_2.52.0        
[58] glue_1.4.2             purrr_0.3.4            processx_3.5.2        
[61] pkgload_1.2.1          fastmap_1.1.0          AnnotationDbi_1.54.1  
[64] sessioninfo_1.1.1      memoise_2.0.0          usethis_2.0.1

**Comment by LiNk-NY** [comment]
Hi @vw087 

Please provide a reproducible example using the `reprex::reprex` function. 
**https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example**
It will ensure that you don't have undefined variables in the reprex (e.g., `keylist`).

Best, 
Marcel

**Comment by vw087** [comment]
Hi Marcel,
It takes long time to run the reprex::reprex() - (it is still running)
Meanwhile, I can assure you all the variables are defined. Please see below the entire code, Thanks so much :)

----------------------------------------------------------------------------
#Load Packages
library(UniProt.ws)
library(dplyr)
library(annotables)
library(tibble)
library(sqldf)

options(url.method="libcurl")
#-----------------------------------

#load uniprot object taxId 9606 is for human
hu <- UniProt.ws(taxId = 9606)

#extract all the ENTREZ_gene names from hu

egs = keys(hu, "ENTREZ_GENE")

#read a input data list

keys_list <- read.csv("Input_data/KEGG_NAD_pathway.csv", header = 1)

keys_list <- keys_list %>% unique()

#keys_list$Entry.name <- gsub("[//_].*","",keys_list$Entry.name)

#merge to get ENTRENZ ID

keylist_m <- merge(keys_list, grch38[, c("entrez", "symbol")], by.x="ï..GENE", by.y="symbol")

#create an index to querry the hu

keysl <- intersect(keylist_m$entrez,egs)

## use select to extract data by the keys of interest

res <- UniProt.ws::select(hu, keys = keylist_m$entrez, columns = c("ENTRY-NAME","SEQUENCE"),keytype = "ENTREZ_GENE")

#---------------------- remove duplicate entries----------------------------#

res <- unique(res)

#----------------------------------------------------------------------------#

 #--extract the motif-but not the position---------------------

#Motifs

#mode I - RXX(pS/pT)XP motifs dominate, and leucine and arginine are the most common residues in the −5 position. Serine and proline
# are the most common residues in the extended sequences flanking the 14-3-3-binding sites.

# ....R/K..S/T.P/S.....

#str_extract(c("Brian", "Brien", "Brin"), "Bri[ae]n") - "a" or "e"

rxxsxpi <- stringr::str_extract_all(res$SEQUENCE, "....[KR]..[ST].[SP].....")
names(rxxsxpi) <- res$`ENTRY-NAME`

#unlist and setnames
rxx_unl <- setNames(unlist(rxxsxpi, use.names=F),rep(names(rxxsxpi), lengths(rxxsxpi)))

rxx_unldf <- cbind(rxx_unl) %>% as.data.frame()

rxx_unldf <- rownames_to_column(rxx_unldf,"Protein")

rxx_unldf$Protein <- gsub("[//_].*","",rxx_unldf$Protein)

colnames(rxx_unldf)<- c("Protein","Motif")

rxx_unldff <- na.omit(rxx_unldf)

write.table(rxx_unldff, '09212020_Transcription_regulators_p14-3-3_motif_prediction.csv',row.names = F,sep=',')

#end of prediction

#-----------Mining_data_from_PhosSitePlus-----------------

#read the phosphosite datset downloaded from -https://www.phosphosite.org/staticDownloads

psite <- read.csv("Input_data/Phosphorylation_site_dataset.csv", sep =",")

psite$GENE <- psite$GENE %>% toupper()

psite$SITE_...7_AA <- psite$SITE_...7_AA %>% toupper()

hpsite <- psite %>% filter(psite$ORGANISM == "human")

colnames(hpsite)[10] <- "AA_Motif"

#use SQL querry to mine hits from the hpsite df

rxxsxpout <- sqldf("SELECT * FROM rxx_unldff JOIN hpsite 
                  ON rxx_unldff.Protein = hpsite.GENE 
                  WHERE rxx_unldff.Motif LIKE hpsite.AA_Motif")

rxxsxpout <- rxxsxpout[,c(1,5,7,10:12)]

write.table(rxxsxpout, '09212020_Transcription_regulators_validated_p14-3-3_moti.csv',row.names = F,sep=',')

#save R session

save.image()

**Comment by vw087** [comment]
Hi. I also tried following to see whether connection works and it seems it does work.

> urls <-   c("https://www.uniprot.org/uniprot/?query=","https://www.uniprot.org/mapping/","http://www.uniprot.org/uniprot/?query=accession:P30443&format=tab&columns=id,sequence","http://www.uniprot.org/uniprot/?query=organism:9606&format=tab&columns=id,sequence","http://www.uniprot.org/uniprot/?query=P04217+or+P30443&format=tab&columns=id,sequence")

> valid_url <- function(url_in,t=2){
+   con <- url(url_in)
+   check <- suppressWarnings(try(open.connection(con,open="rt",timeout=t),silent=T)[1])
+   suppressWarnings(try(close.connection(con),silent=T))
+   ifelse(is.null(check),TRUE,FALSE)
+ }

> sapply(urls,valid_url)
                                              https://www.uniprot.org/uniprot/?query= 
                                                                                 TRUE 
                                                     https://www.uniprot.org/mapping/ 
                                                                                 TRUE 
http://www.uniprot.org/uniprot/?query=accession:P30443&format=tab&columns=id,sequence 
                                                                                 TRUE 
   http://www.uniprot.org/uniprot/?query=organism:9606&format=tab&columns=id,sequence 
                                                                                 TRUE 
http://www.uniprot.org/uniprot/?query=P04217+or+P30443&format=tab&columns=id,sequence 
                                                                                 TRUE 
>

**Comment by LiNk-NY** [comment]
Hi @vw087 

I am still unable to reproduce. I do not have the `csv` file you list here. 
Please read the link and provide a _minimally_ reproducible example.
Be sure to be mindful of the formatting as well as it helps with legibility.
https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example

Please re-open when ready.

Best,
Marcel

**Comment by vw087** [comment]
Hi Marcel,
Apologies, please find the csv file attached below. Thanks so much
Vajira Weerasekara Ph.D.Postdoctoral Research Fellow: Nabeel Bardeesy Laboratory
Massachusetts General Hospital Cancer Center; Harvard Medical School 
185 Cambridge St. CPZN 4100 | Boston, MA 02114 
Phone: Mobile: 801-787-4779 / Office: 617-643-4576 

    On Thursday, August 12, 2021, 12:17:55 PM EDT, Marcel Ramos ***@***.***> wrote:  
 
 


Hi @vw087

I am still unable to reproduce. I do not have the csv file you list here.
Please read the link and provide a minimally reproducible example.
Be sure to be mindful of the formatting as well as it helps with legibility.
https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example

Please re-open when ready.

Best,
Marcel

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
