### ISSUE TITLE
Mapping error

### ISSUE THREAD

**Issue by gerrardmai** [Bioconductor/UniProt.ws#19]
I followed the code you provided:

two error occure:  can not connect to database?
#########
> up
"UniProt.ws" object:
An interface object for UniProt web services
Current Taxonomy ID:
9606
Current Species name:
Homo sapiens
To change Species see: help('availableUniprotSpecies')
> egs=keys(up,"ENTREZ_GENE")
Getting mapping data for Q00266 ... and P_ENTREZGENEID
error while trying to retrieve data in chunk 1:
    no results after 5 attempts; please try again later
continuing to try

#########
> keys<-c("1","2")
> columns<-c("PDB","HGNC","SEQUENCE")
> kt<-"ENTREZ_GENE"
> res<-select(up,keys,columns,kt)
Getting mapping data for 1 ... and ACC
error while trying to retrieve data in chunk 1:
    no results after 5 attempts; please try again later
continuing to try
Error in `colnames<-`(`*tmp*`, value = `*vtmp*`) : 

##########

**Comment by vjcitn** [comment]
It seems to me the web service is very weak and should not be used.  We probably should drop this package.  `keys(up)` is a long operation and I do not want to wait for the result.  But you could run it and save the output for future use.

I did find that upon setting the tax id to mouse, the shortrunning example worked:
```
taxId(up) <- 10090
 res <- select(up, 
                   keys = c("22627","22629"), 
                   columns = c("PDB","HGNC","SEQUENCE"),
                   keytype = "ENTREZ_GENE")
```
produces
```
> str(res)
'data.frame':	2 obs. of  4 variables:
 $ ENTREZ_GENE: chr  "22627" "22629"
 $ PDB        : chr  NA "5YQG"
 $ HGNC       : chr  NA NA
 $ SEQUENCE   : chr  "MDDREDLVYQAKLAEQAERYDEMVESMKKVAGMDVELTVEERNLLSVAYKNVIGARRASWRIISSIEQKEENKGGEDKLKMIREYRQMVETELKLICCDILDVLDKHLIPA"| __truncated__ "MGDREQLLQRARLAEQAERYDDMASAMKAVTELNEPLSNEDRNLLSVAYKNVVGARRSSWRVISSIEQKTMADGNEKKLEKVKAYREKIEKELETVCNDVLALLDKFLIKN"| __truncated__
```

So if you have further concerns please contact the UniProt administrators and ask them whether
there are updated web service endpoints that have better performance.  If you get useful information please
reopen the issue.
