### ISSUE TITLE
Does specifying organism_id in mapUniProt constrain return values to that organism?

### ISSUE THREAD

**Issue by mittimithai** [Bioconductor/UniProt.ws#22]
The following simple example for one gene follows the docs I think:

mapUniProt(
  from = "Gene_Name",
  to = "UniProtKB-Swiss-Prot",
  debug=T,
  columns = c("accession",
             "xref_alphafolddb",
              "xref_pdb",
             "organism_id",
              "xref_chembl",
              "protein_name",
              "xref_geneid"),
   query = list(organism_id = 9606, ids = c("TSPAN6")))

But I get several TSPAN6 genes back from other organisms. Is there an error in my example or has something changed on Uniprot's end for how the organism id is specified?

**Comment by LiNk-NY** [comment]
Hi @mittimithai 

Thanks for opening the issue. It seems like there is additional parameter that can be added when `from = "Gene_Name"` is included. This can be added to the query input as a list element. See the example below. 
I will update the documentation to include this note. 

``` r
suppressPackageStartupMessages(library(UniProt.ws))
mapUniProt(
    from = "Gene_Name",
    to = "UniProtKB-Swiss-Prot",
    debug=TRUE,
    columns = c(
        "accession", "id", "xref_alphafolddb", "xref_pdb",
        "organism_id", "xref_chembl", "protein_name", "xref_geneid"
    ),
    query = list(taxId = 9606, ids = c("TSPAN6"))
)
#> Hitting: https://rest.uniprot.org/idmapping/run
#> Hitting: https://rest.uniprot.org/idmapping/details/fa98f9d878b85ae244e2aa9f0706a7b982547f95
#> Hitting: https://rest.uniprot.org/idmapping/uniprotkb/results/fa98f9d878b85ae244e2aa9f0706a7b982547f95
#>     From  Entry Entry.Name AlphaFoldDB PDB Organism..ID. ChEMBL
#> 1 TSPAN6 O43657 TSN6_HUMAN     O43657;  NA          9606     NA
#>                                                                                                                                                  Protein.names
#> 1 Tetraspanin-6 (Tspan-6) (A15 homolog) (Putative NF-kappa-B-activating protein 321) (T245 protein) (Tetraspanin TM4-D) (Transmembrane 4 superfamily member 6)
#>   GeneID
#> 1  7105;
```

<sup>Created on 2023-02-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Best,
Marcel

**Comment by LiNk-NY** [comment]
@mittimithai 

Note that this is not a feature documented in https://www.uniprot.org/help/query-fields
but it can be seen in this page: https://www.uniprot.org/id-mapping

Best,
Marcel
