### ISSUE TITLE
Error running Uniprot.ws

### ISSUE THREAD

**Issue by Camsid** [Bioconductor/UniProt.ws#25]
Hello all. I am trying to run UniProt.ws retrieving information from Uniprot for Leishmania major. I used it before (June 2024), however now is not working and it's showing me this error:

> UNIPROT <- UniProt.ws(taxId=5664) # Taxon ID of Leishmania major on Uniprot
  |                                                                                               |   0%
Error in validObject(.Object) : 
  invalid class “UniProt.ws” object: 1: invalid object for slot "taxIdUniprots" in class "UniProt.ws": got class "NULL", should be or extend class "character"
invalid class “UniProt.ws” object: 2: invalid object for slot "organism" in class "UniProt.ws": got class "NULL", should be or extend class "character"

I don't know if I am doing something wrong, but I also tried using the example in the manual, but it didn't work either.
Thank you for your time

**Comment by LiNk-NY** [comment]
see #26
