### ISSUE TITLE
Infinite loop for large query?

### ISSUE THREAD

**Issue by Arthfael** [Bioconductor/UniProt.ws#3]
Hi,
I have recently switched to using this very useful package for retrieving GO annotations for my UniProt IDs, it is so far the most complete method of those I have tested, so thanks a lot for making this.

A few days ago I started encountering a strange issue that made me think the code may have recently changed and introduced an infinite loop that only affects large queries. However, it may also be that I am not using it properly, as I was never sure I was doing it right.

My code goes:
```
up <- UniProt.ws(taxId = tx)  # tx = taxon ID
res <- UniProt.ws::select(up, keys = proteins, columns = c("GO","GO-ID"), keytype = "UNIPROTKB") # proteins = non-redundant character vector of ALL UniProt accessions in the species' proteome (removed the "-2", etc... isoform suffix).

Getting extra data for D6RG00,A0A1B0GTD4,F5H7Q5,E0YMJ1,J3KSB8,J3KQ18
'select()' returned 1:1 mapping between keys and columns
...
```

This works nicely with small numbers of IDs, and used to take about 1-2h for all proteins in a proteome. Not ideal, but decent. However a few days ago the same script started never stopping... and when I looked at the protein IDs printed for every sequence of 6 IDs retrieved, I noticed that the script was endlessly looping through the same IDs, even though my proteins character vector is not redundant. I have changed my code to have a loop which now queries only 6 IDs at a time, but this looks like a bug to me.

**On a side note:** if this is not the correct way to do this, I will be happy to correct my code.
To fasten the process and decrease the amount of data I have to collect, I am considering logging all downloaded mappings between accessions and GO annotations into a local database, that way I would only have to query the service with new IDs in future, however I am unsure as to how often GO annotations are updated by UniProt? Is there a benefit to check once in a while that, say, GO annotations for accession "D6RG00" are unchanged since last time?

**Comment by Arthfael** [comment]
An issue which may be related to the cause of the bug:
```
up <- UniProt.ws(taxId = 9606)
res <- select(up, keys = "A2A2A0", columns = c("GO","GO-ID"), keytype = "UNIPROTKB")
Getting extra data for A2A2A0
Getting extra data for A2A2A0
Getting extra data for A2A2A0
```
...
add infinitum...
This only happens if accession "A2A2A0" is part of the keys character vector, is there something about its that structure that results in it not being interpreted correctly?

**Comment by mtmorgan** [comment]
For some reason the query to the uniprot server is failing. I updated UniProt.ws to report why it fails; this won't magically retrieve the data, but might suggest future revisions. You can install this version of the package with

```
BiocInstaller::install("Bioconductor/UniProt.ws")
```

Please follow up here with any feedback on the nature of the problem.

**Comment by Arthfael** [comment]
Hi, I tried using this but got the following error:
```
> BiocInstaller::install("Bioconductor/UniProt.ws")
Error: 'install' is not an exported object from 'namespace:BiocInstaller'
--
```
Is this going to give me a different version than if I do:
```
source("https://bioconductor.org/biocLite.R")
biocLite("UniProt.ws")
```
(which works without problem)

Also, in the meantime I noticed that accession "A2A2A1" results in the same issue, there really does seem to be a pattern, something to do with the unusual, repetitive shape of the accessions. Just in case, I did check and they were listed in the available keys, so that is not the issue.

**Comment by mtmorgan** [comment]
Oops, `BiocInstaller::biocLite("Bioconductor/UniProt.ws"); you'll also need `devtools`, `install.packages("devtools")`. Yes, it will be a different version from `biocLite("UniProt.ws")`.

**Comment by Arthfael** [comment]
OK, I managed to do the update. Now I get this:

```
Getting extra data for A2A2A1
error while trying to retrieve data in chunk 1:
    no results after 5 attempts; please try again later
continuing to try
Warning messages:
1: In file(file, "rt") : InternetOpenUrl failed: 'The operation timed out'
2: In file(file, "rt") : InternetOpenUrl failed: 'The operation timed out'
3: In file(file, "rt") : InternetOpenUrl failed: 'The operation timed out'
4: In file(file, "rt") : InternetOpenUrl failed: 'The operation timed out'
5: In file(file, "rt") : InternetOpenUrl failed: 'The operation timed out'
6: In file(file, "rt") : InternetOpenUrl failed: 'The operation timed out'
```
Would it help if I contacted UniProt directly about this?

**Comment by mtmorgan** [comment]
You could try one more time to update to another modified version `BiocInstaller::biocLite("Bioconductor/UniProt.ws")`; it will report the URL that it is trying, e.g.,

```
reading url
    http://www.uniprot.org/uniprot/?query=A2A2A0&format=tab&columns=id,go,go-id
failed on attempt 1 of 5
```

You could try to paste that url into your browser; I guess it will fail with the underlying problem being on UniProt's side. It would be helpful to then pursue this with UniProt, mentioning the problematic url access through your browser.
