### ISSUE TITLE
not all UniProt IDs are searchable

### ISSUE THREAD

**Issue by biodan25** [Bioconductor/UniProt.ws#4]
While the UniProt.org web site will map terms like APOB_HUMAN to EntrezID, HGNC etc, the UniProt.ws tool doesn't support this field. 

> library(UniProt.ws)
> up <- UniProt.ws(taxId=9606)
> types  <- keytypes(up); types  # 92 are returned

 -  i tried mapping using all the keytypes (starting with kt=UNIPROTKB) and no data is returned.  
 - Am i missing something?

 here is the query 

> keys <- c('APOB_HUMAN','THRB_HUMAN')
> columns <- c("HGNC",'ENTREZ_GENE')
> kt <- 'UNIPROTKB'
> res <- select(up, keys, columns, kt)

  - here is the output ( i actually did this from a command-line script)
Error in .select(x, keys, columns, keytype) : 
  No data is available for the keys provided.
Calls: select -> select -> .select
Execution halted

**Comment by Kayla-Morrell** [comment]
@biodan25 - Having looked at the uniprot website for [APOB](https://www.uniprot.org/uniprot/P04114) and [THRB](https://www.uniprot.org/uniprot/P10828), the keys are incorrect. If you want to use the `UNIPROTKB` keytype the query should look like the following:

```
> keys <- c('P04114', 'P10828')
> columns <- c("HGNC", 'ENTREZ_GENE')
> kt <- 'UNIPROTKB'
> res <- select(up, keys, columns, kt)
Getting mapping data for P04114 ... and P_ENTREZGENEID
Getting mapping data for P04114 ... and HGNC_ID
'select()' returned 1:1 mapping between keys and columns
> res
  UNIPROTKB       HGNC ENTREZ_GENE
1    P04114   HGNC:603         338
2    P10828 HGNC:11799        7068
```
