### ISSUE TITLE
Wrapping package functions into larger functions

### ISSUE THREAD

**Issue by Arthfael** [Bioconductor/UniProt.ws#5]
Hi,
I am encountering a strange error. I had wrapped the package's UniProt.ws and UniProt.ws::select functions into a larger function - and had noticed that it had become slower, but had assumed this was due to the underlying code having changed, since I had updated to a newer version (cf. an issue I reported a few months ago, now solved). I am observing that running the function's script as a script is much faster (maybe 5 times or so!) than calling my wrapper function. Moreover, sometimes the function fails when its script itself succeeds. Any reason why this may be happening, i.e. why running this script's functions inside larger functions is much slower than running them as is?
Kind regards,

Armel

**Comment by mtmorgan** [comment]
UniProt.ws accesses a web service and a much more likely explanation is that your tests just coincide with slow versus fast response; I can think of no reason why running in a script would be appreciably slower than running directly.

**Comment by Arthfael** [comment]
Hum, I was going to say it was unlikely as I had done several tests yesterday, but now I did a more systematic one and you are right. I apologize for wasting your time.
